import plate from "../../static/plate.png";
import plate2 from "../../static/plate2.png";
import plate3 from "../../static/plate4.png";
import plate4 from "../../static/plate3.png";
import burger1 from "../../static/burger1.png";
import burger2 from "../../static/burger2.png";
import burger3 from "../../static/burger3.png";



export const menu=[
    {
      category: "Plates",
      items: [
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicsdas",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
      ],
    },
    {
      category: "Burgers",
      items: [
        { nametop: "Beaf",namebottom:"Burger",description:"",price:"9", image: burger1 },
        { nametop: "Double Beaf",namebottom:"Burger",description:"",price:"7", image: burger2 },
        {  nametop: "Chicken",namebottom:"Burger",description:"",price:"11",image: burger3 },
        { nametop: "Beaf",namebottom:"Burger",description:"",price:"9", image: burger1 },
        { nametop: "Double Beaf",namebottom:"Burger",description:"",price:"7", image: burger2 },
        {  nametop: "Chicken",namebottom:"Burger",description:"",price:"11",image: burger3 },
        { nametop: "Beaf",namebottom:"Burger",description:"",price:"9", image: burger1 },
        { nametop: "Double Beaf",namebottom:"Burger",description:"",price:"7", image: burger2 },
        {  nametop: "Chicken",namebottom:"Burger",description:"",price:"11",image: burger3 },
        { nametop: "Beaf",namebottom:"Burger",description:"",price:"9", image: burger1 },
        { nametop: "Double Beaf",namebottom:"Burger",description:"",price:"7", image: burger2 },
        {  nametop: "Chicken",namebottom:"Burger",description:"",price:"11",image: burger3 },
      ],
    },
    { category: "Drinks",  items: [
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicsdas",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
      ], },
    { category: "Coffea",  items: [
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicsdas",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
      ], },
    { category: "Offers",  items: [
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicsdas",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
      ],},
    { category: "Appetizers",  items: [
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicsdas",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate3 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate4 },
        {  nametop: "Boneless",namebottom:"Chicken",description:"",price:"9", image: plate2 },
      ], },
  ];